# Generated by Django 3.2.16 on 2024-04-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name_plural': 'FOODITEM'},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canteen.category'),
            preserve_default=False,
        ),
    ]
