# Generated by Django 3.2.16 on 2024-04-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_auto_20240417_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
