# Generated by Django 4.1.3 on 2023-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_cart_is_paid_orders_payment_gateway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('booked_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
