# Generated by Django 4.1.3 on 2023-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
